### ISSUE TITLE
Class GuzzleCache not found

### ISSUE THREAD

**Issue by MaggieRezo** [RemiCollin/GuzzleCache#3]
I get Class 'App\GuzzleCache' not found when I try to implement it.

**Comment by RemiCollin** [comment]
Did you register the facade in your config/app.php ?

**Comment by MaggieRezo** [comment]
The providers and the aliases like your readme says, yes.

**Comment by RemiCollin** [comment]
Just realized @iBourgeois used a wrong namespace for the facades. 
Corrected it, please run composer update and try again.
Thanks for pointing this out.

**Comment by MaggieRezo** [comment]
I did but I have the same problem. Do I need to add anything before the class/controller where I'm using it? 
I only have this right now:

use \GuzzleHttp\Client;

**Comment by RemiCollin** [comment]
Yes, as the controllers are in their own namespace, you need to add :

```
use GuzzleCache;
```

**Comment by MaggieRezo** [comment]
Ok, now it works, thanks a lot!

**Comment by RemiCollin** [comment]
You're welcome!
